version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/Appliscale/Cloud-Security-Audit-Serverless
    steps:
      - checkout
      - run: make get-deps
      - run: make code-analysis
      - run: make test

  release:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/Appliscale/Cloud-Security-Audit-Serverless
    steps:
      - checkout
      - run: make
      - run: mkdir -p release
      - run:
          name: "Build Cloud Security Audit for Linux"
          command: |
            GOOS=linux GOARCH=amd64 go build -o release/cloud-security-audit-linux-amd64
            tar -C release -czf release/cloud-security-audit-linux-amd64.tar.gz cloud-security-audit-linux-amd64
      - run:
          name: "Build Cloud Security Audit for Darwin"
          command: |
            GOOS=darwin GOARCH=amd64 go build -o release/cloud-security-audit-darwin-amd64
            tar -C release -czf release/cloud-security-audit-darwin-amd64.tar.gz cloud-security-audit-darwin-amd64
      - run:
          name: "Get gothub"
          command: |
            go get github.com/itchio/gothub
      - run:
          name: "Publish release on github"
          command: |
            gothub upload --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name "cloud-security-audit-darwin-amd64" --file release/cloud-security-audit-darwin-amd64.tar.gz
            gothub upload --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name "cloud-security-audit-linux-amd64" --file release/cloud-security-audit-linux-amd64.tar.gz


workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^v\d+\.\d+(\.\d+)?$/
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+(\.\d+)?$/
